blank_issues_enabled: false
contact_links:
  - name: 'â“ Discussion Board'
    url: https://github.com/coravel-rs/coravel/discussions/categories/q-a
    about: Ask your questions here
  - name: 'ğŸ“¢ Support Policy'
    url: https://github.com/coravel-rs/.github/blob/main/docs/SUPPORT.md
    about: Learn how to get help here
